- name: Rollback redmine app
  hosts: all
  become: yes
  tags: app
  tasks:
    - name: Delete readmine container
      community.docker.docker_container:
        name: redmine
        state: absent
      ignore_errors: yes

    - name: Delete environment file
      file:
        path: '{{ app_env }}'
        state: absent
      ignore_errors: yes

    - name: Delete app directory
      file:
        path: '{{ app_dir }}'
        state: absent
      ignore_errors: yes

- name: Rollback Datadog Agent
  hosts: webservers
  become: yes
  tags: dd
  tasks:
    - name: Remove datadog-agent package with purge
      apt:
        name: datadog-agent
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove dd-agent user and home directory
      user:
        name: dd-agent
        state: absent
        remove: yes

    - name: Remove leftover directories
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - /opt/datadog-agent
        - /etc/datadog-agent
        - /var/log/datadog
